use super::TestApi;
use crate::{connector::Queryable, single::Quaint};
use names::Generator;
use quaint_test_setup::Tags;
use std::{env, sync::LazyLock};

pub static CONN_STR: LazyLock<String> =
    LazyLock::new(|| env::var("TEST_KINGBASE_ORACLE").expect("TEST_KINGBASE_ORACLE env var"));

pub(crate) async fn kingbase_oracle_test_api<'a>() -> crate::Result<KingbaseOracle<'a>> {
    KingbaseOracle::new(CONN_STR.as_str()).await
}

/// Test API for KingbaseES in Oracle-compatible mode.
///
/// This is intentionally independent from both the PostgreSQL and Kingbase
/// MySQL test APIs: it owns Oracle-mode DDL, quoting, identity columns and the
/// mode-specific connection URL.
pub struct KingbaseOracle<'a> {
    names: Generator<'a>,
    conn: Quaint,
    conn_str: String,
}

impl<'a> KingbaseOracle<'a> {
    pub async fn new(conn_str: &str) -> crate::Result<Self> {
        Ok(Self {
            names: Generator::default(),
            conn: Quaint::new(conn_str).await?,
            conn_str: conn_str.to_owned(),
        })
    }
}

#[async_trait::async_trait]
impl TestApi for KingbaseOracle<'_> {
    fn system(&self) -> &'static str {
        "kingbase_oracle"
    }

    async fn create_type_table(&mut self, r#type: &str) -> crate::Result<String> {
        self.create_temp_table(&format!("{}, value {type}", self.autogen_id("id")))
            .await
    }

    async fn create_temp_table(&mut self, columns: &str) -> crate::Result<String> {
        let name = self.get_name();
        let (name, create) = self.render_create_table(&name, columns);

        self.conn().raw_cmd(&create).await?;

        Ok(name)
    }

    async fn create_table(&mut self, columns: &str) -> crate::Result<String> {
        let name = self.get_name();
        self.conn()
            .raw_cmd(&format!("CREATE TABLE \"{name}\" ({columns})"))
            .await?;

        Ok(name)
    }

    async fn delete_table(&mut self, table_name: &str) -> crate::Result<()> {
        self.conn().raw_cmd(&format!("DROP TABLE \"{table_name}\"")).await
    }

    fn render_create_table(&mut self, table_name: &str, columns: &str) -> (String, String) {
        (
            table_name.to_owned(),
            format!("CREATE TEMPORARY TABLE \"{table_name}\" ({columns})"),
        )
    }

    async fn create_index(&mut self, table: &str, columns: &str) -> crate::Result<String> {
        let name = self.get_name();
        self.conn()
            .raw_cmd(&format!("CREATE UNIQUE INDEX \"{name}\" ON \"{table}\" ({columns})"))
            .await?;

        Ok(name)
    }

    fn conn(&self) -> &Quaint {
        &self.conn
    }

    async fn create_additional_connection(&self) -> crate::Result<Quaint> {
        Quaint::new(&self.conn_str).await
    }

    fn create_pool(&self) -> crate::Result<crate::pooled::Quaint> {
        Ok(crate::pooled::Quaint::builder(&CONN_STR)?.build())
    }

    fn unique_constraint(&mut self, column: &str) -> String {
        format!("UNIQUE({column})")
    }

    fn foreign_key(&mut self, parent_table: &str, parent_column: &str, child_column: &str) -> String {
        let name = self.get_name();
        format!("CONSTRAINT \"{name}\" FOREIGN KEY ({child_column}) REFERENCES \"{parent_table}\"({parent_column})")
    }

    fn autogen_id(&self, name: &str) -> String {
        // Oracle-mode Kingbase only accepts an identity declaration on an
        // integer-family column, not on NUMBER.
        format!("{name} INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    }

    fn get_name(&mut self) -> String {
        self.names.next().unwrap().replace('-', "")
    }

    fn connector_tag(&self) -> Tags {
        Tags::KINGBASE_ORACLE
    }
}
