use sql_introspection_tests::test_api::*;
use test_macros::test_connector;

#[test_connector(tags(KingbaseOracle))]
async fn oracle_native_type_columns_are_introspected(api: &mut TestApi) -> TestResult {
    api.raw_cmd(
        r#"
        CREATE TABLE native_types (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tinyint_value TINYINT NOT NULL,
            int_value NUMBER(10, 0) NOT NULL,
            bigint_value NUMBER(19, 0) NOT NULL,
            decimal_value NUMBER(12, 4) NOT NULL,
            binary_float_value BINARY_FLOAT NOT NULL,
            binary_double_value BINARY_DOUBLE NOT NULL,
            char_value CHAR(10) NOT NULL,
            varchar_value VARCHAR2(32) NOT NULL,
            clob_value CLOB NOT NULL,
            nclob_value NCLOB NOT NULL,
            blob_value BLOB NOT NULL,
            date_value DATE NOT NULL,
            timestamp_value TIMESTAMP(3) NOT NULL,
            timestamp_tz_value TIMESTAMP(3) WITH TIME ZONE NOT NULL,
            bool_value BOOLEAN NOT NULL,
            json_value JSON NOT NULL,
            uuid_value UUID NOT NULL,
            xml_value XML NOT NULL
        );
        "#,
    )
    .await;

    let dml = api.introspect_dml().await?;
    let expected = expect![[r#"
        model native_types {
          id                  Int      @id @default(autoincrement())
          tinyint_value       Int      @db.TinyInt
          int_value           Int
          bigint_value        BigInt
          decimal_value       Decimal  @db.Number(12, 4)
          binary_float_value  Float    @db.BinaryFloat
          binary_double_value Float
          char_value          String   @db.Char(10)
          varchar_value       String   @db.VarChar2(32)
          clob_value          String   @db.Clob
          nclob_value         String   @db.Clob
          blob_value          Bytes
          date_value          DateTime @db.Timestamp(0)
          timestamp_value     DateTime
          timestamp_tz_value  DateTime @db.TimestampTz(3)
          bool_value          Boolean
          json_value          Json
          uuid_value          String   @db.Uuid
          xml_value           String   @db.Xml
        }
    "#]];

    expected.assert_eq(&dml);

    Ok(())
}

#[test_connector(tags(KingbaseOracle))]
async fn oracle_national_and_local_timezone_types_follow_catalog_canonicalization(api: &mut TestApi) -> TestResult {
    api.raw_cmd(
        r#"
        CREATE TABLE oracle_type_variants (
            id INTEGER PRIMARY KEY,
            nchar_value NCHAR(4) NOT NULL,
            nvarchar_value NVARCHAR2(32) NOT NULL,
            local_tz_value TIMESTAMP(6) WITH LOCAL TIME ZONE NOT NULL
        );
        "#,
    )
    .await;

    let result = api.introspect_dml().await?;

    for expected in ["nchar_value", "nvarchar_value", "local_tz_value", "@db.Timestamp(6)"] {
        assert!(result.contains(expected), "missing `{expected}` in:\n{result}");
    }

    Ok(())
}

#[test_connector(tags(KingbaseOracle))]
async fn oracle_number_precision_boundaries_are_introspected(api: &mut TestApi) -> TestResult {
    api.raw_cmd(
        r#"
        CREATE TABLE number_boundaries (
            id INTEGER PRIMARY KEY,
            single_digit_value NUMBER(1) NOT NULL,
            boolean_value BOOLEAN NOT NULL,
            int_value NUMBER(10) NOT NULL,
            bigint_value NUMBER(19) NOT NULL,
            decimal_value NUMBER(20) NOT NULL
        );
        "#,
    )
    .await;

    let result = api.introspect_dml().await?;

    for (field, scalar) in [
        ("single_digit_value", "Int"),
        ("boolean_value", "Boolean"),
        ("int_value", "Int"),
        ("bigint_value", "BigInt"),
        ("decimal_value", "Decimal"),
    ] {
        assert!(
            result.lines().any(|line| line.contains(field) && line.contains(scalar)),
            "missing `{field} {scalar}` in:\n{result}"
        );
    }

    Ok(())
}
