use sql_introspection_tests::test_api::*;
use test_macros::test_connector;

#[test_connector(tags(KingbaseOracle))]
async fn oracle_defaults_and_indexes_are_introspected(api: &mut TestApi) -> TestResult {
    api.raw_cmd(
        r#"
        CREATE TABLE table_features (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_id NUMBER(10, 0) NOT NULL,
            required_label VARCHAR2(64) NOT NULL,
            optional_label VARCHAR2(64),
            attempts NUMBER(10, 0) NOT NULL DEFAULT 3,
            created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
            quote_text VARCHAR2(64) NOT NULL DEFAULT 'O''Reilly',
            unique_code VARCHAR2(32) NOT NULL,
            binary_data BLOB,
            CONSTRAINT table_features_tenant_code_key UNIQUE (tenant_id, unique_code)
        );

        CREATE INDEX table_features_required_label_idx ON table_features (required_label ASC);
        "#,
    )
    .await;

    let expected = expect![[r#"
        model table_features {
          id             Int      @id @default(autoincrement())
          tenant_id      Int
          required_label String   @db.VarChar2(64)
          optional_label String?  @db.VarChar2(64)
          attempts       Int      @default(3)
          created_at     DateTime @default(now())
          quote_text     String   @default("O'Reilly") @db.VarChar2(64)
          unique_code    String   @db.VarChar2(32)
          binary_data    Bytes?

          @@unique([tenant_id, unique_code], map: "table_features_tenant_code_key")
          @@index([required_label])
        }
    "#]];

    expected.assert_eq(&api.introspect_dml().await?);

    Ok(())
}

#[test_connector(tags(KingbaseOracle))]
async fn oracle_non_id_identity_and_string_defaults_are_introspected(api: &mut TestApi) -> TestResult {
    api.raw_cmd(
        r#"
        CREATE TABLE identity_features (
            id INTEGER PRIMARY KEY,
            generated_value INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
            empty_label VARCHAR2(32) NOT NULL DEFAULT '',
            status VARCHAR2(32) NOT NULL DEFAULT 'pending'
        );

        CREATE INDEX identity_features_status_idx ON identity_features (status ASC, empty_label DESC);
        "#,
    )
    .await;

    let result = api.introspect_dml().await?;

    for expected in [
        "generated_value Int    @unique @default(autoincrement())",
        "empty_label     String @db.VarChar2(32)",
        "status          String @default(\"pending\")",
        "@@index([status, empty_label(sort: Desc)]",
    ] {
        assert!(result.contains(expected), "missing `{expected}` in:\n{result}");
    }

    // Oracle-compatible catalogs normalize an empty string default to no default value.
    assert!(!result.contains("empty_label     String @default"), "{result}");

    Ok(())
}

#[test_connector(tags(KingbaseOracle))]
async fn oracle_function_and_escaped_string_defaults_are_introspected(api: &mut TestApi) -> TestResult {
    api.raw_cmd(
        r#"
        CREATE TABLE expression_defaults (
            id INTEGER PRIMARY KEY,
            calculated_value NUMBER(10, 0) DEFAULT (ABS(8) + ABS(8)),
            quote_value VARCHAR2(500) NOT NULL DEFAULT '"That''s a lot of fish!"\n - Godzilla, 1998',
            backslash_value VARCHAR2(255) NOT NULL DEFAULT 'xyz\Datasource\Model'
        );
        "#,
    )
    .await;

    let result = api.introspect_dml().await?;

    assert!(result.contains("calculated_value"), "{result}");
    assert!(result.contains("@default(dbgenerated("), "{result}");
    assert!(result.contains("Godzilla, 1998"), "{result}");
    assert!(result.contains("xyz\\\\Datasource\\\\Model"), "{result}");

    Ok(())
}
